config/routes.rb
Rails.application.routes.draw do

  resources :activations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :personals
  resources :services do
    resources :comments
  end
  resources :news
  resources :contacts 
  resources :rents do
    member {get :more}
  end
  resources :searches do
    member {get :more}
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :sales do
    member {get :more}
  end
  resources :purchases do
    member {get :more}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_one_attached :image
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :image
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :service
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  validates :name, presence: true, length: {minimum: 2}




  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :file, attachment: true
  attribute :sender, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :phone
  validates :phone, :presence => {:message => 'hello world, bad operation!'},
                    :numericality => true,
                    :length => { :minimum => 12, :maximum => 12 }

  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "Сообшение от сайта TIJEGLI HYZMAT",
      to: "tijeglihyzmat@gmail.com",
      from: %("#{name}" <#{sender}>)
    }
  end
end

app/models/dealdone.rb
class Dealdone < ApplicationRecord
  has_one_attached :image
end

app/models/favicon.rb
class Favicon < ApplicationRecord
  has_one_attached :image
end

app/models/key.rb
class Key < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_one_attached :image
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
  has_one_attached :image
end

app/models/nophoto.rb
class Nophoto < ApplicationRecord
  has_one_attached :image
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :type
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :sale
  has_many :purchase
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :region
  belongs_to :typesofrent
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :type
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :region
  belongs_to :typesofrent
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
  has_many_attached :iamges
  has_many :comments
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :purchase
  has_many :sale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  def login
    @login || self.username || self.email
  end

  # app/models/user.rb

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if (login = conditions.delete(:login))
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
    def validate_username
      if User.where(email: username).exists?
        errors.add(:username, :invalid)
      end
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @keys = Key.all
    @keys.each do |key|
      if key.key != @activation

          redirect_to '/admin'


      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<head>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css">
  <link rel="stylesheet" href="/css/slider.css">
  <script src=/js/slider.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.parallax {
    /* The image used */
    background-image: url("images/img_parallax.jpg");

    /* Set a specific height */
    min-height: 500px;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
</style>
</head>

<div class="owl-carousel slide-one-item">



<% @banners.each do |banner| %>
  <div class="site-section-cover overlay img-bg-section" style="background-image: url(<%= rails_blob_url(banner.image)%>);" >
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-12 col-lg-7">
          <h1 data-aos="fade-up" data-aos-delay="">
            <%= banner.title_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
            <%= banner.title_ru if params[:locale] == 'ru' %>
            <%= banner.title_tm if params[:locale] == 'tm' %>
          </h1>
          <p class="mb-5" data-aos="fade-up" data-aos-delay="100">
            <%= banner.text_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
            <%= banner.text_ru if params[:locale] == 'ru' %>
            <%= banner.text_tm if params[:locale] == 'tm' %>
          </p>
          <p data-aos="fade-up" data-aos-delay="200">
            <%= link_to banner.link + "#{params[:locale]}", class:'btn btn-outline-white border-w-2 btn-md' do %>
            <%= t('see')%>
            <% end %>
          </p>
        </div>
      </div>
    </div>

  </div>
<% end %>
  <!--<div class="site-section-cover overlay img-bg-section" style="background-image: url('images/yyy.jpeg'); " >
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-12 col-lg-8">
          <h1 data-aos="fade-up" data-aos-delay="">Вы не начали</h1>
          <p class="mb-5" data-aos="fade-up" data-aos-delay="100">Тогда мы идём к Вам!</p>
          <p data-aos="fade-up" data-aos-delay="200"><a href="#" class="btn btn-outline-white border-w-2 btn-md">Дать себе заработать</a></p>
        </div>
      </div>
    </div>

  </div>
  <div class="site-section-cover overlay img-bg-section" style="background-image: url('images/hero_1.jpg'); " >
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-12 col-lg-8">
          <h1 data-aos="fade-up" data-aos-delay="">Вы не начали</h1>
          <p class="mb-5" data-aos="fade-up" data-aos-delay="100">Тогда мы идём к Вам!</p>
          <p data-aos="fade-up" data-aos-delay="200"><a href="#" class="btn btn-outline-white border-w-2 btn-md">Дать себе заработать</a></p>
        </div>
      </div>
    </div>

  </div>-->
</div>
<div class="novana_ulanekas_wrapper">

  <div class="novana_ulanekas">
    <center>
    <h1><%= t('news')%></h1>
    </center>
    <div class="novana_ulanekas__wrp swiper-wrapper">
      <!-- Карточка -->
      <% @news.each do |new| %>
        <div class="novana_ulanekas__item swiper-slide">
          <div class="novana_ulanekas__img">
            <% if new.image.attached? %>
            <%= image_tag(new.image) %>
            <% else %>
            <%= image_tag(@no)%>
            <% end %>
          </div>
            <div class="novana_ulanekas__content">
              <span class="novana_ulanekas__date"><%= new.created_at %></span>
              <div class="novana_ulanekas__title">
                <%= new.title_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru'%>
                <%= new.title_ru if params[:locale] == 'ru'%>
                <%= new.title_tm if params[:locale] == 'tm'%>
              </div>
              <p><%= simple_format new.text_ru.length <= 300 ? new.text_ru : new.text_ru[0..300] + '...' if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru'%></p>
              <p><%= simple_format new.text_ru.length <= 300 ? new.text_ru : new.text_ru[0..300] + '...' if params[:locale] == 'ru' %></p>
              <p><%= simple_format new.text_tm.length <= 300 ? new.text_tm : new.text_tm[0..300] + '...' if params[:locale] == 'tm' %></p>
              <div class="novana_ulanekas__button-wrapper">
                <%= link_to news_path(new), class:'novana_ulanekas__button' do %>
                <%= t('more')%>
                <% end %>
              </div>
            </div>
        </div>
      <% end %>
  <!-- Еще карточки -->

  <!-- Карточка -->

  <!-- Еще карточки -->

  <!-- Карточка -->

  <!-- Еще карточки -->

  </div>
  <div class="gecadesa_sudelaye_akoaces"></div>
  </div>
</div>




<div class="parallax" id="p1">
  <br><br><br><br><br>
  <div class="container">
  <% @abouts.each do |about| %>
    <center>
      <h1>
        <%= about.title_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
        <%= about.title_ru if params[:locale] == 'ru' %>
        <%= about.title_tm if params[:locale] == 'tm' %>
      </h1>
    </center>
    <div class="row">
      <div class="col">
        <%= image_tag(about.image) %>
      </div>
      <div class="col">
        <%= simple_format about.text_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
        <%= simple_format about.text_ru if params[:locale] == 'ru' %>
        <%= simple_format about.text_tm if params[:locale] == 'tm' %>
      </div>

    </div>

  <% end %>
  </div>
  <br><br><br>
</div>

<div class="footer2" id="footer2" style="background-color: rgba(0, 120, 201, 0.7);">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6">

        <div class="form-wrapper">
        <%= form_for @contact do |f| %>
        <div class="contact-form">

          <h2 class="contact-form__title"><%= t('contact.write') %></h2>
          <div class="contact-form__input-wrapper">

            <%= f.text_field :name, class:'contact-form__input contact-form__input_name', placeholder: t('contact.name')%>
          </div>
        <div class="contact-form__input-wrapper">
          <%= f.email_field :email, class:'contact-form__input contact-form__input_email', placeholder:'E-mail' %>
        </div>
        <div class="contact-form__input-wrapper">
          <%= f.text_field :phone, class:'contact-form__input contact-form__input_tel', placeholder: t('sales.phone')  %>
        </div>
        <div class="contact-form__input-wrapper">
        <%= f.text_area :message, class:'form-control', rows:'8' %>
        </div>
          <div class="contact-form__input-wrapper">
            <%= f.file_field :file, class:'form-control', type:'file', id:'formFileMultiple' %>
          </div>
        <center>
        <%= f.submit t('contact.send'), class:'btn btn-success'%>
        </center>
        <% end %>
        </div>

        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="form-wrapper" style="min-height: 729px">
          <div class="contact-form" style="min-height: 669px">
            <h2 class="contact-form__title"><%= t('contact.contacts') %></h2>
              <% @contactdetails.each do |c| %>

                <div class="">
                  <h4>
                  <%= t('contact.address')%>
                  <%= c.address_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                  <%= c.address_ru if params[:locale] == 'ru' %>
                  <%= c.address_tm if params[:locale] == 'tm' %>
                  </h4>
                </div>
                <hr>
                <div class="">
                  <h4>
                  <%= t('contact.phone')%>
                  <a href="tel:<%= c.phone1 %>"><%= c.phone1 %></a>;
                  <a href="tel:<%= c.phone2 %>"><%= c.phone2 %></a>
                  </h4>
                </div>
                <hr>
                <div class="">
                  <h4>
                  <%= t('contact.mail')%>
                  <%= mail_to c.email1 %>;
                  <%= mail_to c.email2 %>
                  </h4>
                </div>
                <hr>
              <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <% flash.each do |type, msg| %>
  <div class="alert alert-danger">
    <center><%= msg %></center>
  </div>
  <% end %>
</div>
<script type="text/javascript">
  var swiper = new Swiper('.novana_ulanekas', {
  autoplay: true,
  smartSpeed: 2000,
  autoplayTimeout: 10000,
  effect: 'fade',
  loop: true,

  autoHeight: true,
  pagination: {
  el: '.gecadesa_sudelaye_akoaces',
  clickable: true,

  }
});

</script>