config/routes.rb
Rails.application.routes.draw do

  resources :activations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :personals
  resources :services do
    resources :comments
  end
  resources :news
  resources :contacts 
  resources :rents do
    member {get :more}
  end
  resources :searches do
    member {get :more}
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :sales do
    member {get :more}
  end
  resources :purchases do
    member {get :more}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_one_attached :image
end

app/models/aboutimage.rb
class Aboutimage < ApplicationRecord
  has_one_attached :image
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :image
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :service
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  validates :name, presence: true, length: {minimum: 2}




  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :file, attachment: true
  attribute :sender, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :phone
  validates :phone, :presence => {:message => 'hello world, bad operation!'},
                    :numericality => true,
                    :length => { :minimum => 12, :maximum => 12 }

  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "Сообшение от сайта TIJEGLI HYZMAT",
      to: "tijeglihyzmat@gmail.com",
      from: %("#{name}" <#{sender}>)
    }
  end
end

app/models/dealdone.rb
class Dealdone < ApplicationRecord
  has_one_attached :image
end

app/models/favicon.rb
class Favicon < ApplicationRecord
  has_one_attached :image
end

app/models/key.rb
class Key < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_one_attached :image
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
  has_one_attached :image
end

app/models/nophoto.rb
class Nophoto < ApplicationRecord
  has_one_attached :image
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :type
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :sale
  has_many :purchase
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :region
  belongs_to :typesofrent
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :type
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :region
  belongs_to :typesofrent
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
  has_many_attached :iamges
  has_many :comments
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :purchase
  has_many :sale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  def login
    @login || self.username || self.email
  end

  # app/models/user.rb

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if (login = conditions.delete(:login))
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
    def validate_username
      if User.where(email: username).exists?
        errors.add(:username, :invalid)
      end
    end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  def index
  end
  def show
    @keys = Key.all
    @keys.each do |key|
      if key.key != @activation

          redirect_to '/admin'


      end
    end
    @labelrent = Typesofrent.find(params[:id])
    @searches = Search.where(public: true)
    @searches1 = @searches.where(typesofrent_id: params[:id])
    @searches2 =  @searches1.order "busy ASC"
    @nophoto = Nophoto.all

    @nophoto.each do |nophoto|
      @no = nophoto.image
    end
  end
  def more
    @labelrent = Typesofrent.find(params[:id])
    @searches = Search.where(public: true)
    @searches1 = @searches.where(typesofrent_id: params[:id])
    @keys = Key.all
    @keys.each do |key|
      if key.key != @activation

          redirect_to '/admin'


      end
    end
    @nophoto = Nophoto.all

    @nophoto.each do |nophoto|
      @no = nophoto.image
    end
    @search = Search.find(params[:id])
    @regions = Region.where(id: @search.region_id)
    @regions.each do |region|
      @region = region
    end
    @brands = Brand.where(id: @search.brand_id)
    @brands.each do |brand|
      @brand = brand
    end
    @models = Model.where(id: @search.model_id)
    @models.each do |model|
      @model = model
    end
  end
  def new
    @regions = Region.all
    @typesofrents = Typesofrent.all
    @brands = Brand.all
    @models = Model.all
  end
  def create
    @search = Search.new(search_params)
    @search.username_id = current_user.id
    if @search.save
      redirect_to personals_path
    else
      render action: 'new'
    end
  end
  def edit
    @regions = Region.all
    @typesofrents = Typesofrent.all
    @brands = Brand.all
    @models = Model.all

    @search = Search.find(params[:id])
    if @search.username_id != current_user.id
      redirect_to personals_path
    end
  end
  def update
  @search = Search.find(params[:id])
  if @search.update(search_params)
    redirect_to personals_path
  else
    render action: 'edit'
  end
  end



private

  def search_params
    params.require(:search).permit(:title_ru, :title_tm, :title_en, :text_ru, :text_tm, :text_en, :region_id, :year, :typesofrent_id, :phone, :price, :email, :public, :cashless, :brand_id, :model_id, :name, :username, :username_id, :busy)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <br><br><br><br>

      <%= form_for :search, url: search_path(@search), method: :put do |f| %>
      <div class="container">
        <div class="">
          <%= f.label t('rent.busy') %>
          <%= f.check_box :busy %>
        </div>
        <center>


          <%= f.label t('rent.title'), class:'form-label' %>
          <% if params[:locale] == 'ru' %>
            <%= f.text_field :title_ru, class:'form-control', style:'width: absolute' %>
          <% elsif params[:locale] == 'tm'%>
            <%= f.text_field :title_tm, class:'form-control', style:'width: absolute' %>
          <% end %>
        </center>
        <center>
          <%= f.label t('rent.text'), class:'form-label' %>
          <% if params[:locale] == 'ru' %>
            <%= f.text_area :text_ru, class:'form-control', style:'width: absolute' %>
          <% elsif params[:locale] == 'tm'%>
            <%= f.text_area :text_tm, class:'form-control', style:'width: absolute' %>
          <% end %>
        </center>
    <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-6 col-md-4">
          <%= f.label t('sales.brand') %>
          <%= f.select(:brand_id, [], {}, { :class => 'form-control' }) do %>
            <%= @brands.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id ) %>
            <% end %>
          <% end %>


        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('rent.typeteh') %>
          <%= f.select(:typesofrent_id, [], {}, { :class => 'form-control' }) do %>
            <%= @typesofrents.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id ) if params[:locale] == 'ru'%>
              <%= content_tag(:option, c.name_tm, value: c.id ) if params[:locale] == 'tm' %>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.region') %>
          <%= f.select(:region_id, [], {}, { :class => 'form-control' }) do %>
            <%= @regions.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id ) if params[:locale] == 'ru' %>
              <%= content_tag(:option, c.name_tm, value: c.id ) if params[:locale] == 'tm' %>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.brand') %>
          <%= f.select(:model_id, [], {}, { :class => 'form-control' }) do %>
            <%= @models.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id )%>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.year') %>
          <%= f.text_field :year, :class => 'form-control' %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.price') %>
          <%= f.text_field :price, :class => 'form-control' %>
          <%= f.label t('sales.cashless') %>
          <%= f.check_box :cashless %>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">

    </div>

    <div class="container">
      <div class="row">
        <div class="col-6 col-md-4">
          <%= f.label t('sales.phone') %>
          <%= f.text_field :phone, :class => 'form-control' %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label 'Email' %>
          <%= f.text_field :email, class:'form-control', placeholder: t('no_write'), value:"#{current_user.email}" %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('name_user') %>
          <%= f.text_field :name, :class => 'form-control', value:"#{current_user.username}" %>
        </div>
      </div>
      <hr>
    </div>

    <center>
      <div class="mb-3">
        <%= f.label t('photo'), for:'formFile', class:'form-label' %>
        <%= f.file_field :image, class:'form-control', type:'file', id:'formFile', style:'width: 400px' %>
      </div>
      <div class="mb-3">
      <%= f.label t('photos'), for:'formFile', class:'form-label' %>
      <%= f.file_field :images, multiple: true, class:'form-control', type:'file', id:'formFileMultiple', style:'width: 400px' %>
    </div>
    <p><%= f.submit t('change'), class:'btn btn-success' %></p>
    <% end %>
    </center>


  </body>
</html>

app/views/searches/more.html.erb
<center>
  <h1><%= t('search_show')%></h1>
  <h2>

    <%= @labelrent.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
    <%= @labelrent.name if params[:locale] == 'ru' %>
    <%= @labelrent.name_tm if params[:locale] == 'tm' %>
  </h2>

</center>


<% if @search != nil %>
  <div class="container" style="background-color: rgba(169,169,169, 0.2);">
  <h1>
  <%= @search.title_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
  <%= @search.title_ru if params[:locale] == 'ru' %>
  <%= @search.title_tm if params[:locale] == 'tm' %>
  <% if current_user %>
    <% if current_user.id == @search.username_id %>
      <%= link_to edit_search_path(@search) do %>
        <span class="icon-pencil"></span>
      <% end %>
    <% end %>
  <% end %>
  </h1>
<div class="card" style="width: 10rem;">
  <% if @search.image.attached? %>
    <%= image_tag(@search.image)%>
  <% else %>
    <%= image_tag(@no) %>
  <% end %>
  </div>
  <hr>
  <%= t('sales.brand')%><div><%= @brand.name %></div>
  <hr>
  <% if @search.model_id == nil %>
    <%= t('sales.model')%><div><%= t('sales.nomodel')%></div>
  <% else %>
    <%= t('sales.model')%><div><%= @model.name %></div>
  <% end %>
  <hr>
  <%= t('sales.year')%><div><%= @search.year %></div>
  <hr>
  <%= t('sales.price')%><div><%= @search.price %></div>
  <hr>
  <%= t('sales.about')%>
  <div>
    <%= @search.text_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
    <%= @search.text_ru if params[:locale] == 'ru' %>
    <%= @search.text_tm if params[:locale] == 'tm' %>
  </div>
  <hr>
    <%= t('sales.phones')%><div><a href="tel:<%= @search.phone %>"><%= @search.phone %></a></div>
  <hr>
    E-mail:
  <div>
    <%= mail_to @search.email %>
  </div>
  <hr>
  <%= check_box_tag 'admin', '1', @search.cashless, :disabled => true %><%= t('sales.cashless') %>
  <hr>
  <%= @region.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
  <%= @region.name if params[:locale] == 'ru' %>
  <%= @region.name_tm if params[:locale] == 'tm' %>
  <hr>
  <div class="row">
    <% @search.images.each do |image|%>
      <div class="col-6 col-md-2">

          <%= image_tag(image, class:'productsimages rounded open-popup')%>

      </div>


  <% end %>
  </div>
  </div>
  <% elsif %>
  <div class="parallax">
    <%= image_tag(@dealdone, style:'width: 100%; opacity:.2;') %>
    <center>
    <div class="centered">

      <%= t('purchase.purchase')%>

      <%= link_to root_path, class:'btn btn-light' do %>
        <%= t('sale.sales_back')%>

    </div>
    </center>
    <% end %>
<% end %>
</div>
<br>

app/views/searches/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <br><br><br><br>

      <%= form_for :searches, url: searches_path do |f| %>
      <div class="container">
        <center>
          <%= f.label t('rent.title'), class:'form-label' %>
          <% if params[:locale] == 'ru' %>
            <%= f.text_field :title_ru, class:'form-control', style:'width: absolute' %>
          <% elsif params[:locale] == 'tm'%>
            <%= f.text_field :title_tm, class:'form-control', style:'width: absolute' %>
          <% end %>
        </center>
        <center>
          <%= f.label t('rent.text'), class:'form-label' %>
          <% if params[:locale] == 'ru' %>
            <%= f.text_area :text_ru, class:'form-control', style:'width: absolute' %>
          <% elsif params[:locale] == 'tm'%>
            <%= f.text_area :text_tm, class:'form-control', style:'width: absolute' %>
          <% end %>
        </center>
    <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-6 col-md-4">
          <%= f.label t('sales.brand') %>
          <%= f.select(:brand_id, [], {}, { :class => 'form-control' }) do %>
            <%= @brands.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id ) %>
            <% end %>
          <% end %>


        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('rent.typeteh') %>
          <%= f.select(:typesofrent_id, [], {}, { :class => 'form-control' }) do %>
            <%= @typesofrents.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id ) if params[:locale] == 'ru'%>
              <%= content_tag(:option, c.name_tm, value: c.id ) if params[:locale] == 'tm' %>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.region') %>
          <%= f.select(:region_id, [], {}, { :class => 'form-control' }) do %>
            <%= @regions.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id ) if params[:locale] == 'ru' %>
              <%= content_tag(:option, c.name_tm, value: c.id ) if params[:locale] == 'tm' %>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.brand') %>
          <%= f.select(:model_id, [], {}, { :class => 'form-control' }) do %>
            <%= @models.each do |c| %>
              <%= content_tag(:option, c.name, value: c.id )%>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.year') %>
          <%= f.text_field :year, :class => 'form-control' %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('sales.price') %>
          <%= f.text_field :price, :class => 'form-control' %>
          <%= f.label t('sales.cashless') %>
          <%= f.check_box :cashless %>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">

    </div>

    <div class="container">
      <div class="row">
        <div class="col-6 col-md-4">
          <%= f.label t('sales.phone') %>
          <%= f.text_field :phone, :class => 'form-control' %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label 'Email' %>
          <%= f.text_field :email, class:'form-control', placeholder: t('no_write'), value:"#{current_user.email}" %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.label t('name_user') %>
          <%= f.text_field :name, :class => 'form-control', value:"#{current_user.username}" %>
        </div>
      </div>
      <hr>
    </div>

    <center>
      <div class="mb-3">
        <%= f.label t('photo'), for:'formFile', class:'form-label' %>
        <%= f.file_field :image, class:'form-control', type:'file', id:'formFile', style:'width: 400px' %>
      </div>
      <div class="mb-3">
      <%= f.label t('photos'), for:'formFile', class:'form-label' %>
      <%= f.file_field :images, multiple: true, class:'form-control', type:'file', id:'formFileMultiple', style:'width: 400px' %>
    </div>
    <p><%= f.submit t('publication'), class:'btn btn-success' %></p>
    <% end %>
    </center>


  </body>
</html>

app/views/searches/show.html.erb
<center>
  <h1><%= t('search_show')%></h1>
  <h2>

    <%= @labelrent.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
    <%= @labelrent.name if params[:locale] == 'ru' %>
    <%= @labelrent.name_tm if params[:locale] == 'tm' %>
  </h2>

</center>


<h1></h1>
<center>
<%= link_to new_search_path do %>
  <%= t("rent.add")%>
<% end %>
</center>

<div class="novana_ulanekas_wrapper">

  <div class="novana_ulanekas">

  <% @searches2.each do |search| %>
    <div class="site-section">
      <div class="block__73694 mb-2" id="services-section">
        <div class="container">
          <div class="row d-flex no-gutters align-items-stretch">
            <div class="col-6 col-md-3 block__73422" data-aos="fade-right" data-aos-delay="">
              <div class="card" style="width: 10rem;">
            <% if search.image.attached? %>
              <%= image_tag(search.image) %>
            <% else %>
              <%= image_tag(@no) %>
            <% end %>
            </div>
            <%= check_box_tag 'admin', '1', search.busy, :disabled => true %><%= t('rent.busy') %>
            </div>
            <div class="col-6 col-md-9 block__73422" data-aos="fade-left" data-aos-delay="">
              <h2 class="mb-3 text-black"><%= search.title_ru if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %></h2>
              <h2 class="mb-3 text-black"><%= search.title_ru if params[:locale] == 'ru' %></h2>
              <h2 class="mb-3 text-black"><%= search.title_tm if params[:locale] == 'tm' %></h2>
              <% if search.text_ru != nil %>
              <p><%= simple_format search.text_ru.length <= 100 ? search.text_ru : search.text_ru[0..100] + '...' if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru'%></p>
              <p><%= simple_format search.text_ru.length <= 100 ? search.text_tm : search.text_tm[0..100] + '...' if params[:locale] == 'tm' %></p>
              <% elsif search.text_tm != nil %>
              <p><%= simple_format search.text_tm.length <= 100 ? search.text_ru : search.text_ru[0..100] + '...' if params[:locale] == 'ru' %></p>
              <% end %>
              <%= link_to more_search_path(search) do %>
                <%= t('more')%>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>
</div>