config/routes.rb
Rails.application.routes.draw do

  resources :activations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :personals
  resources :services do
    resources :comments
  end
  resources :news
  resources :contacts 
  resources :rents do
    member {get :more}
  end
  resources :searches do
    member {get :more}
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :sales do
    member {get :more}
  end
  resources :purchases do
    member {get :more}
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_one_attached :image
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :image
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :service
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  validates :name, presence: true, length: {minimum: 2}




  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :file, attachment: true
  attribute :sender, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :phone
  validates :phone, :presence => {:message => 'hello world, bad operation!'},
                    :numericality => true,
                    :length => { :minimum => 12, :maximum => 12 }

  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "Сообшение от сайта TIJEGLI HYZMAT",
      to: "tijeglihyzmat@gmail.com",
      from: %("#{name}" <#{sender}>)
    }
  end
end

app/models/dealdone.rb
class Dealdone < ApplicationRecord
  has_one_attached :image
end

app/models/favicon.rb
class Favicon < ApplicationRecord
  has_one_attached :image
end

app/models/key.rb
class Key < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_one_attached :image
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
  has_one_attached :image
end

app/models/nophoto.rb
class Nophoto < ApplicationRecord
  has_one_attached :image
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :type
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :sale
  has_many :purchase
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :region
  belongs_to :typesofrent
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :type
  belongs_to :region
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :region
  belongs_to :typesofrent
  belongs_to :brand
  belongs_to :model
  has_one_attached :image
  has_many_attached :images
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
  has_many_attached :iamges
  has_many :comments
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :purchase
  has_many :sale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  def login
    @login || self.username || self.email
  end

  # app/models/user.rb

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if (login = conditions.delete(:login))
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
    def validate_username
      if User.where(email: username).exists?
        errors.add(:username, :invalid)
      end
    end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HK "TIJEGLI HYZMAT"</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,700|Oswald:400,700" rel="stylesheet">

    <link rel="stylesheet" href="/fonts/icomoon/style.css">

    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="/css/aos.css">
    <link rel="stylesheet" href="/css/earth.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css">
    <link rel="stylesheet" href="/css/slider.css">
    <script type="text/javascript" src="/js/tab.js"></script>

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/css/style.css">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div id="overlayer"></div>
  <div class="loader">
    <div class="spinner-border text-primary" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>

  <div class="site-wrap"  id="home-section">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>


    <div class="top-bar" style="opacity: .5">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <% @contactdetails.each do |c| %>
            <%= mail_to c.email1, class:'text-white' do %>
              <span class="mr-2 text-white icon-envelope-open-o"></span> <span class="d-none d-md-inline-block"><%= c.email1%></span>
            <% end %>
            <span class="mx-md-2 d-inline-block"></span>
            <!--<a href="#" class="text-white"><span class="mr-2 text-white icon-phone"></span> <span class="d-none d-md-inline-block">+ (993) 65555555</span></a>-->
            <%= phone_to c.phone1, class:'text-white' do %>
              <span class="mr-2 text-white icon-phone"></span> <span class="d-none d-md-inline-block"><%= c.phone1%></span>
            <% end %>
            <% end %>

            <div class="float-right">



            <% if current_user  %>
              <%= current_user.username %>|
              <%= link_to t('quit'), destroy_user_session_path, method: :delete, class:'text-white' %>
            <% else %>
              <%= link_to personals_path do %>
                <span class="mr-2 text-white icon-person"></span>
              <% end %>
            <% end %>
            <span class="mx-md-2 d-inline-block"></span>

              <% if current_user %>
                <%= link_to personals_path do %>
                  <span class="mr-2 text-white icon-person"></span>
                <% end %>
              <% end %>
              <%= link_to 'TM', url_for(locale: :tm), :class => "ml-auto text-white" if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
              <%= link_to 'TM', url_for(locale: :tm), :class => "ml-auto text-white" if params[:locale] == 'ru' %>
              <%= link_to 'RU', url_for(locale: :ru), :class => "ml-auto text-white" if params[:locale] == 'tm' %>
            </div>


          </div>

        </div>

      </div>
    </div>

    <header class="site-navbar js-sticky-header site-navbar-target" role="banner">

      <div class="container">
        <div class="row align-items-center position-relative">


            <div class="site-logo">
              <%= link_to root_path, class:'text-black' do %>
              
                <span class="text-primary">TIJEGLI HYZMAT</span>
              <% end %>
              <!--<a href="index.html" class="text-black"><span class="text-primary">TIJEGLI HYZMAT</a>-->
            </div>

            <div class="col-12">
              <nav class="site-navigation text-right ml-auto " role="navigation" style="font-size: 11px">

                <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
                <!--<li>

                  <%= link_to root_path do %>
                    <%= t('navbar.main')%>
                  <% end %>
                </li>-->
                <li>
                  <% @service_link.each do |link| %>
                    <%= link_to service_path(link) do %>
                      <%= link.name_ru.capitalize if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                      <%= link.name_ru.capitalize if params[:locale] == 'ru' %>
                      <%= link.name_tm.capitalize if params[:locale] == 'tm' %>
                    <% end %>
                  <% end %>
                </li>

                <li class="has-children">
                  <a href="#about-section" class="nav-link"><%= t('navbar.comm_services')%></a>

                  <ul class="dropdown arrow-top">
                    <li class="has-children">
                      <a href="#"><%= t('navbar.sale')%></a>
                      <ul class="dropdown">
                          <% @types.each do |type| %>
                          <li>
                            <%= link_to sale_path(type) do %>
                            <%= type.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru' %>
                            <%= type.name if params[:locale] == 'ru' %>
                            <%= type.name_tm if params[:locale] == 'tm' %>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </li>
                    <li class="has-children">
                      <a href="#"><%= t('navbar.purchase')%></a>
                      <ul class="dropdown">
                          <% @types.each do |type| %>
                          <li>
                            <%= link_to purchase_path(type) do %>
                              <%= type.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru'%>
                              <%= type.name if params[:locale] == 'ru' %>
                              <%= type.name_tm if params[:locale] == 'tm' %>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li class="has-children">
                  <a href="#about-section" class="nav-link"><%= t('navbar.rent').capitalize %></a>

                  <ul class="dropdown arrow-top">
                    <li class="has-children">
                      <a href="#"><%= t('navbar.rents')%></a>
                      <ul class="dropdown">
                          <% @typesofrent.each do |type| %>
                          <li>
                            <%= link_to rent_path(type) do %>
                            <%= type.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru'%>
                            <%= type.name if params[:locale] == 'ru' %>
                            <%= type.name_tm if params[:locale] == 'tm' %>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </li>
                    <li class="has-children">
                      <a href="#"><%= t('navbar.search')%></a>
                      <ul class="dropdown">
                          <% @typesofrent.each do |type| %>
                          <li>
                            <%= link_to search_path(type) do %>
                              <%= type.name if params[:locale] != true and params[:locale] != 'tm' and params[:locale] != 'ru'%>
                              <%= type.name if params[:locale] == 'ru' %>
                              <%= type.name_tm if params[:locale] == 'tm' %>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li>
                  <!--<a href="#services-section" class="nav-link">Услуги</a>-->
                  <%= link_to services_path do %>
                    <%= t('navbar.services') %>
                  <% end %>
                </li>
                <li><!--<a href="#press-section" class="nav-link">О нас</a>-->
                    <% if current_page?(root_path)%>
                      <%= link_to '#p1' do %>
                        <%= t('navbar.about')%>
                      <% end %>
                    <% end %>
                    <% unless current_page?(root_path) %>
                      <%= link_to root_path + '#p1' do %>
                        <%= t('navbar.about')%>
                      <% end %>
                    <% end %>
                </li>
              </ul>
              </nav>

            </div>

          <div class="toggle-button d-inline-block d-lg-none"><a href="#" class="site-menu-toggle py-5 js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>

        </div>
      </div>

    </header>












    <%= yield %>

<div>
    <footer class="site-footer" style="opacity: .7" id="footer">
      <strong>

      <div class="container">
        <div class="border-top pt-5 text-center">
          <p class="copyright"><small>
            Copyright &copy;<%= @time.year %> "TIJEGLI HYZMAT" All rights reserved
          </small></p>
        </div>
      </div>
      </strong>
    </footer>

  </div>

  <script src="/js/popper.min.js"></script>
  <script src="/js/jquery-3.3.1.min.js"></script>
  <script src="/js/bootstrap.min.js"></script>
  <script src="/js/owl.carousel.min.js"></script>
  <script src="/js/jquery.sticky.js"></script>
  <script src="/js/jquery.waypoints.min.js"></script>
  <script src="/js/jquery.animateNumber.min.js"></script>
  <script src="/js/jquery.fancybox.min.js"></script>
  <script src="/js/jquery.easing.1.3.js"></script>
  <script src="/js/aos.js"></script>

  <script src="/js/main.js"></script>

  </body>
</html>

app/views/layouts/create.js.erb
// app/views/home/create.js.erb

// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);